### ISSUE TITLE
More Native Protocols

### ISSUE THREAD

**Issue by sirinath** [jvirtanen/nassau#22]
Leveraging from some of the other projects you have been involved in is it possible to add more native protocols.

**Comment by jvirtanen** [comment]
I would like to keep this project focused on the NASDAQ transport protocols, because those are stable, reliable, and applicable to a wide variety of applications. The NASDAQ application protocols, such as ITCH and OUCH, belong to [Juncture](https://github.com/jvirtanen/juncture), and the new FIX engine will be a separate project.

Regarding past projects, right now I am not particularly interested in adding support for the NASDAQ OMX Nordic transport protocols. On the other hand, support for [UFO](http://www.nasdaqtrader.com/content/technicalsupport/specifications/tradingproducts/ufo.pdf) would be an interesting addition. Contributions are welcome! :wink:

Do you have some particular protocols in mind?

**Comment by sirinath** [comment]
Keep all the them separate and publish them on maven. I like to contribute a trading engine. In order to do this is it possible to have the feed handler and order flow interfaces defined in a generic way. I am going to code against this interface. One more protocols become available them can be used.

**Comment by jvirtanen** [comment]
It sounds like you might already have a good idea on what the generic feed handler and order entry interfaces should look like. Would you be interested in starting such a project? I would gladly help on integrating Nassau, Juncture, and the forthcoming FIX engine to it.

**Comment by jvirtanen** [comment]
@sirinath By the way, have you seen [Helix](https://github.com/penberg/helix), @penberg's recently released market data feed handler for C and C++?

**Comment by sirinath** [comment]
Seen it. I am looking for something in Java and which has a very generic interface so the protocols can be plugged in.

**Comment by jvirtanen** [comment]
Alright. At the moment I don't have a clear vision on how such system should look like. If you have ideas, I suggest you go forward an initiate such a project. As I mentioned, I would be interested in integrating Nassau and Juncture to it. :+1:

In the meantime I'm following Helix for ideas on the topic and gaining experience from different trading venues via Juncture.

**Comment by sirinath** [comment]
OK. Sounds good.

When I have something I will get back to you. The interface part you might also need to be a bit active so things do not drift too far that it cannot integrate.

**Comment by jvirtanen** [comment]
Sure, just let me know when you have something cooking. :+1:
